export class DataMeteo{
  constructor(
    public moonrise_ts: number,
    public wind_cdir :String,
    public rh:number,
    public pres:number,
    public high_temp:number,
    public sunset_ts:number,
    public ozone:number,
    public moon_phase:number,
    public wind_gust_spd:number,
    public snow_depth:number,
    public clouds:number,
    public ts:number,
    public sunrise_ts:number,
    public app_min_temp:number,
    public wind_spd:number,
    public pop:number,
    public wind_cdir_full:String,
    public slp:number,
    public moon_phase_lunation:number,
    public valid_date:String,
    public app_max_temp:number,
    public vis:number,
    public dewpt:number,
    public snow:number,
    public uv:number,
    public weather:Object,
    public wind_dir:number,
    public max_dhi:null,
    public clouds_hi:number,
    public precip:number,
    public low_temp:number,
    public max_temp:number,
    public moonset_ts:number,
    public datetime:String,
    public temp:number,
    public min_temp:number,
    public clouds_mid:number,
    public clouds_low:number
  ){}
}
