stages:
  - deploy

pages:
  image: angular/ngcontainer
  stage: deploy
  script:
    - npm install
    - ng build
    - mkdir .public
    - cp dist/pecadille .public
    - mv .public public
  artifacts:
    paths:
      - public
  
  
