image: node:16.15

# This is the stages / task to perfom in jobs
stages:
  - build
  - deploy
    
# This command is run before the execution of stages    
before_script:
    - npm install -g @angular/cli@13.3.5
    - npm install

# Job One for making build
build_master: 
  stage: build
  script:
  - ng build
  only: ['master']

# Job Two for deploy build to S3
deploy_master:
  image: python:latest  
  stage: deploy
  before_script:
    - pip install awscli 
  script:
    - aws s3 sync ./public s3://vallagarde-myapp/ --acl=public-read --delete
  only: ['master']
