image: node:latest

pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli
    - npm install
    - ng build --base-href "/pecadille/"
  artifacts:
    paths:
      - public
