stages:
  - deploy

pages:
  image: node:12-alpine
  stage: deploy
  script:
    - yarn install
    - yarn ng build --prod
    - mkdir .public
    - cp dist/pecadille .public
    - mv .public/pecadille public
  artifacts:
    paths:
      - public
  
  
