stages:
  - deploy


pages:
  image: node:16.15-alpine
  stage: deploy
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@10.2.0
    - npm install
    - ng build --prod --base-href /pecadille/
    - mkdir -p public
    - mv dist/pecadille/* public/
  artifacts:
    paths:
      - public
  
  
