stages:
  - deploy

pages:
  image: node:12-alpine
  stage: deploy
  script:
    - yarn install
    - yarn ng build --prod --href /pecadille/
    - mkdir .public
    - cp -r dist/pecadille .public
    - mv .public/pecadille public
  artifacts:
    paths:
      - public
  
  
